name: dartsv
description: Dart Library for interacting with the Bitcoin network. This library is especially well-suited for use in developing Flutter applications.
version: 1.0.0
homepage: https://github.com/twostack/dartsv

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  hex: ^0.2.0
  resource_portable: ^3.0.0
  pointycastle: ^3.3.4
  collection: ^1.15.0
  sprintf: ^6.0.0
  unorm_dart: ^0.2.0
  buffer: ^1.1.1

dev_dependencies:
  lints : ^1.0.1
  test: ^1.18.2
  mockito: ^5.0.16
