name: dartsv
description: Dart Library for interacting with the Bitcoin network. This library is especially well-suited for use in developing Flutter applications.
version: 2.0.0-rc3
homepage: https://github.com/twostack/dartsv

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  hex: ^0.2.0
  resource_portable: ^3.1.0
  pointycastle: ^3.7.0
  sprintf: ^7.0.0
  unorm_dart: ^0.2.0
  buffer: ^1.1.1
  collection: ^1.17.1
  decimal: ^2.3.3

dev_dependencies:
  lints : ^2.1.1
  test: ^1.18.2
  mockito: ^5.0.16
